### PR TITLE
Notify stream acceptor conn down

### LINKED ISSUE #118: accept_stream hangs when connection dies
If client end dies, accept_stream hangs with a `{quic, closed, Conn}` message in the message queue.
A possible fix is:
```
accept_stream(Conn, Opts, Timeout) when is_list(Opts) ->
  accept_stream(Conn, maps:from_list(Opts), Timeout);
accept_stream(Conn, Opts, Timeout) when is_map(Opts) ->
  % @todo make_ref
  % @todo error handling
  NewOpts = maps:merge(default_stream_opts(), Opts),
  case quicer_nif:async_accept_stream(Conn, NewOpts) of
    {ok, Conn} ->
      receive
        {quic, new_stream, Stream} ->
          {ok, Stream};
        {quic, closed, Conn} ->
          {error, connection_closed}

      after Timeout ->
          {error, timeout}
      end;
    {error, _} = E ->
      E
  end.
```

### LINKED ISSUE #127: stream deallocated  when it is not closed
caught in a PR:
https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334

test case: 

`tc_stream_send_shutdown_complete`

This is assertion error, but the test was executed without lttng/snk log.
```
Program terminated with signal SIGABRT, Aborted.
[546](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:547)
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
[547](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:548)
[Current thread is 1 (Thread 0x7fab74e0f700 (LWP 1921))]
[548](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:549)
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
[549](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:550)
#1  0x00007fabb8a45859 in __GI_abort () at abort.c:79
[550](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:551)
#2  0x00007fabb8a45729 in __assert_fail_base (
[551](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:552)
    fmt=0x7fabb8bdb588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
[552](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:553)
    assertion=0x7fab4e95a06e "s_ctx->is_closed == TRUE", 
[553](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:554)
    file=0x7fab4e95a020 "/home/runner/work/quic/quic/c_src/quicer_nif.c", 
[554](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:555)
    line=791, function=<optimized out>) at assert.c:92
[555](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:556)
#3  0x00007fabb8a56fd6 in __GI___assert_fail (
[556](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:557)
    assertion=0x7fab4e95a06e "s_ctx->is_closed == TRUE", 
[557](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:558)
    file=0x7fab4e95a020 "/home/runner/work/quic/quic/c_src/quicer_nif.c", 
[558](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:559)
    line=791, 
[559](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:560)
    function=0x7fab4e95b5e0 <__PRETTY_FUNCTION__.23883> "resource_stream_dealloc_callback") at assert.c:101
[560](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:561)
#4  0x00007fab4e74f581 in resource_stream_dealloc_callback (
[561](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:562)
    env=0x7fab74e0a7e0, obj=0x55969b6471e8)
[562](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:563)
    at /home/runner/work/quic/quic/c_src/quicer_nif.c:791
```

### PR DESCRIPTION
**Pull request by qzhuyan**
fix #118 
fix #127

### CODE REVIEW

File: test/quicer_snb_SUITE.erl [hunk 1]
```diff
@@ -1707,6 +1755,16 @@ quicer_start_listener(Name, Port, Options, N) ->
       Error
   end.
 
+wait_for_die([]) ->
```
Comment (ieQu1) [inline test/quicer_snb_SUITE.erl:1758]: Nit: use monitor?

**Review by ieQu1 — DISMISSED** [review]

File: src/quicer.erl [hunk 2]
```diff
@@ -439,7 +439,10 @@ accept_stream(Conn, Opts, Timeout) when is_map(Opts) ->
     {ok, Conn} ->
       receive
         {quic, new_stream, Stream, _StreamFlags} ->
-          {ok, Stream}
+          {ok, Stream};
+        {quic, closed, undefined, undefined} ->
+          ?tp(debug, stream_accepter_conn_closed, #{ conn => Conn }),
```
Comment (thalesmg) [inline src/quicer.erl:444]:
```suggestion
          ?tp(debug, stream_acceptor_conn_closed, #{ conn => Conn }),
```
?

**Review by thalesmg — APPROVED** [review]

**Review by ieQu1 — APPROVED** [review]
